version: '3.8'

services:
  web:
    build: ./
    command: >
      sh -c "python src/manage.py makemigrations &&
             python src/manage.py migrate &&
             python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
