# Generated by Django 4.1.6 on 2023-02-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='год выпуска')),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='songbook.artist', verbose_name='исполнитель')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songbook.album', verbose_name='альбом')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songbook.song', verbose_name='песня')),
            ],
            options={
                'unique_together': {('album', 'song')},
            },
        ),
    ]
