# Generated by Django 4.1.6 on 2023-02-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0002_alter_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='songbook.artist', verbose_name='исполнитель'),
        ),
        migrations.AlterField(
            model_name='sequencenumber',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_numbers', to='songbook.album', verbose_name='альбом'),
        ),
        migrations.AlterField(
            model_name='sequencenumber',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_numbers', to='songbook.song', verbose_name='песня'),
        ),
    ]
